Добавляет общие стили
Natalia-doobro/Oh-My-Donut pull request #3
Opened 2021-05-13 18:06 UTC by vitalii-shulga

2021-05-13 19:26 UTC, Natalia-doobro requested changes

2021-05-13 19:26 UTC, Natalia-doobro commented on src/sass/components/_container.scss
> +  }
@media screen and (min-width: **$mobile**) {
    width: **$mobile**;
  }
лучше написать так .

2021-05-13 19:26 UTC, Natalia-doobro commented on src/sass/components/_socials.scss
> +}
я думаю на данном этапе  это правило не  требуется , лучше добавить его по мере надобности .

2021-05-13 19:26 UTC, Natalia-doobro commented on src/sass/base/_common.scss
> +  color: #2e2520;
используй переменную

2021-05-14 00:32 UTC, vitalii-shulga commented on src/sass/components/_socials.scss
> +}
исправил на flex, чтобы расположить горизонтально

2021-05-14 00:32 UTC, vitalii-shulga commented on src/sass/base/_common.scss
> +  color: #2e2520;
исправил

2021-05-14 00:36 UTC, vitalii-shulga commented on src/sass/components/_container.scss
> +  }
Поправил. Но видел на trello есть инуформауия как это сделать с помощью @mixin и @include. Может и нам так попробовать?

2021-05-14 01:46 UTC, vitalii-shulga commented on src/sass/components/_container.scss
> +  }
Как то так:
`
@mixin for-mobile-up {
  @media screen and (min-width: 320px) { @content; }
}

@mixin for-mobile-only {
  @media screen and (max-width: 767.9px) { @content; }
}

@mixin for-tablet-up {
  @media screen and (min-width: 768px) { @content; }
}

@mixin for-tablet-only {
  @media screen and (min-width: 768px) and (max-width: 1279.9px) { @content; }
}

@mixin for-tablet-down {
  @media screen and (max-width: 1279.9px) { @content; }
}

@mixin for-desktop-up {
  @media screen and (min-width: 1280px) { @content; }
}
`

2021-05-14 02:05 UTC, vitalii-shulga commented on src/sass/components/_container.scss
> +  }
Писанины вроде много, но все находится в одном файле _breakpoints.sass, так что при необходимости менять нужно только здесь. И sass в конечном итоге выглядит чище. Вызов медиа через @include:
`
@include for-mobile-up {
    width: 320px;
  }

@include for-tablet-down {
    margin-bottom: 20px;
  }
`

2021-05-14 07:54 UTC, Natalia-doobro commented on src/sass/components/_socials.scss
> +}
Я бы пока не добавила flex в базовых стилях , когда начнется работа с этим блоком тогда и следует их добавлять , может возникнуть такой конфликт что у вас разметка так позволяет, а например на футере может быть другая вложенность и там будут проблемы (а мы можем не заметить откуда ошибка). Поэтому порошу пока с базовых стилей убрать флексы .

2021-05-14 07:55 UTC, Natalia-doobro commented on src/sass/components/_socials.scss
> +}
насчет цвета надо поднять вопрос всем в slack

2021-05-14 08:29 UTC, vitalii-shulga commented on src/sass/components/_socials.scss
> +}
Ок. Тогда и правые марджины уберу. Нет в них необходимости без флекса.

2021-05-14 14:23 UTC, Natalia-doobro requested changes

2021-05-14 14:23 UTC, Natalia-doobro commented on src/sass/components/_buttons.scss
> +  height: 40px;
Вчера проверила , и забыла поправить .  Убери пожалуйста от сюда флекс , и ширину, и высоту они здесь не уместны , кнопка блоковый элемент и поэтому спокойно работает без флекса замени лучше на 
```
padding: 12px 47px 13px 46px;
  text-align: center;
```
повторюсь флекс на базовых элементах использовать не стоит .

Там возникнет проблема со шрифтом( line-height: 3.61;)  , там выходит сильный отступ с верху и с низу , пока замени на ( line-height: 1.5;) , а я потом с Алёной обговорю .

2021-05-14 14:23 UTC, Natalia-doobro commented on src/sass/components/_buttons.scss
> +    height: 45px;
убери высоту и ширину

2021-05-14 14:39 UTC, Natalia-doobro commented on src/sass/components/_container.scss
> +  }
идея хорошая , но думаю не всем будет удобно с ней работать (нету времени разбирать остальным ). я заметила что у ребят еще есть проблемы в работе с кодам и  некоторым сложно осваиваться в быстром темпе. Так что я думаю оставить так для большего удобства , метод понятный и простой + все с ним уже столкнулись .

2021-05-14 14:43 UTC, vitalii-shulga commented on src/sass/components/_container.scss
> +  }
Ок, согласен. Сам впервые увидел, показалось удобно.

2021-05-14 14:51 UTC, vitalii-shulga commented on src/sass/components/_buttons.scss
> +  height: 40px;
Там со шрифтами повсюду такая проблема. 
Флекс задан чтобы выровнять контент по центру. Если будем задавать размер кнопки паддингами, у нас не получится общих стилей для 'Register' и 'Send', т.к. длина текста разная. Мне больше нравиться флексом, но если хочешь паддингами тогда надо убрать правый и левый. Что скажешь?

2021-05-14 15:31 UTC, Natalia-doobro commented on src/sass/components/_buttons.scss
> +  height: 40px;
Оставим через падинг , со значением 12px 47px 13px 46px; он повторяется дважды , а для кнопки 'Send', просто переименуем во время стилизации . Флекс хороший способ решить эту проблему но его использование в базовых стилях может испортить работу в финале. Спасибо за понимание .

2021-05-14 15:39 UTC, vitalii-shulga commented on src/sass/components/_buttons.scss
> +  height: 40px;
Ок. Тогда еще вопрос: откуда верхний и нижний паддинги 12px и 13px? При подсчете получается высота кнопки 18px * 1.5 + 12px + 13px = 52px, вместо 40px на макете (для мобильной версии).

2021-05-14 16:14 UTC, vitalii-shulga commented on src/sass/components/_buttons.scss
> +  height: 40px;
Сделал как ты просила. Потом при стилизации будет видко, что получается.

2021-05-14 16:16 UTC, vitalii-shulga commented on src/sass/components/_buttons.scss
> +  height: 40px;
Добавил также фоновые кружочки на иконки соцсетей. Сделал флексом чтобы выровнять иконку в кружочке, т.к. размеры иконок разные и паддингами не получиться.

2021-05-14 16:17 UTC, vitalii-shulga commented on src/sass/components/_buttons.scss
> +    height: 45px;
Убрал.

2021-05-14 18:43 UTC, Natalia-doobro approved these changes

2021-05-14 18:43 UTC, merged